[NFC] Refactor EZPreferencesWindowController into Swift
tisfeng/Easydict pull request #202
Opened 2023-10-28 15:37 UTC by Kyle-Ye

A base PR to migrate Preferences System into Swift.

Also [MASPreferences](https://github.com/shpakovski/MASPreferences) is a very old framework written by ObjectiveC and it has been archived by the owner on Mar 6, 2023.

Can we consider migrating into other modern Swifty framework? eg. [Settings](https://github.com/sindresorhus/Settings)

2023-10-28 17:01 UTC, Kyle-Ye commented
干掉 MASPreferences 后就不用 Easydict 自己维护一套 DarkManager 了，可以直接走 Color Asset 就行。
目前 MASPreferences 下使用这套看起来会有 bug 😂

2023-10-29 02:47 UTC, tisfeng commented
可以的，之前我想重构设置页时也看过 [Settings](https://github.com/sindresorhus/Settings) ，只是担心一下改动太大，不好维护，现在有你来负责 Swift 改造自然是好的 😃

用 SwiftUI 也是可以的，只是重构尽量和之前保持一致，一步步来，保持平稳过渡。

前期我可能没办法给到帮助，Swift 部份代码需要你来维护，辛苦了。

2023-10-29 02:49 UTC, tisfeng requested changes

2023-10-29 02:49 UTC, tisfeng commented on Easydict.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = $CODE_SIGN_IDENTITY;
你好，请问这里是什么改动？

2023-10-29 04:09 UTC, Kyle-Ye commented on Easydict.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = $CODE_SIGN_IDENTITY;
之前 PR 的 CODE_SIGN_IDENTITY = xx 是手写修改的，习惯性加上 "" 防止空格转义，这里在 Xcode 15 下打开触发了该文件的Xcode内部编辑（添加删除了部分文件）后自动被 format 去掉了。

就这样改下吧，不然后续其他人每次增删文件后都会有这个 diff

2023-10-29 04:11 UTC, Kyle-Ye commented
> 用 SwiftUI 也是可以的，只是重构尽量和之前保持一致，一步步来，保持平稳过渡。

Sure. Let's do it step by step. 🚀

2023-10-29 13:58 UTC, tisfeng approved these changes

2023-10-29 13:58 UTC, merged