[WIP][Optimize] Migrate to use Settings & SwiftUI
tisfeng/Easydict pull request #212
Opened 2023-10-30 16:10 UTC by Kyle-Ye

<img width="612" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/b4d6aaf2-4a84-40a7-abf5-d0884d3c4761">

Less and clean code :)

2023-11-03 16:15 UTC, tisfeng commented
你好，最近可能要发一个简单的修复版本，为避免影响，建了一个 [swift-migration](https://github.com/tisfeng/Easydict/tree/swift-migration) 分支，后续关于 swift 的迁移代码可以推到这个分支上。

2023-11-06 02:56 UTC, Kyle-Ye commented
> 你好，最近可能要发一个简单的修复版本，为避免影响，建了一个 [swift-migration](https://github.com/tisfeng/Easydict/tree/swift-migration) 分支，后续关于 swift 的迁移代码可以推到这个分支上。

好的，那我把相关 PR 的 target 都从 tisfeng/dev 改到 tisfeng/swift-migration，等时机合入后再统一 tisfeng/swift-migration 合入 tisfeng/dev？

2023-11-06 03:02 UTC, tisfeng commented
是的，目前只有你这两个在进行中的 PR 需要转到 swift-migration，其他我已经弄过来了。

2023-12-28 16:51 UTC, Kyle-Ye commented
This is ready for a merge. I'd like to get this merged since the new Key Config GUI depends on this PR.

2023-12-28 16:52 UTC, Kyle-Ye commented
It is guarded by a beta toggle "Enable New App". So the impact will be minimal.

2023-12-29 02:13 UTC, tisfeng requested changes

2023-12-29 02:13 UTC, tisfeng commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
这个是用的了什么吗，要求 macOS 13+ ？

2023-12-29 02:15 UTC, Kyle-Ye commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
task 需要 macOS 12+，这个 View 整体是被 MenuBarExtra 消费，需要 macOS 13+
https://developer.apple.com/documentation/swiftui/menubarextra

2023-12-29 02:19 UTC, Kyle-Ye commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
Settings 只需要 macOS 11+，但是内部实现中会用到 macOS 12+ / macOS 13+ 的API
线上其实OC代码已经有用 macOS 12+ 代码了，而且还忘记判断可用性了

https://github.com/tisfeng/Easydict/blob/1645498505e4ca8da32ade49d65b88522cf7d22b/Easydict/Feature/PerferenceWindow/EZPrivacyViewController.m#L145-L155

Line 150 行无效，Line 151 的图片资源需要 macOS 12+，因此咱们在 macOS 11 上这里会显示空白而非兜底的 toolbar_privacy 图片

<img width="336" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/2e36880e-8933-4121-a332-4a0a97054704">

而且貌似这个兜底图片也比较离谱 2x 和 3x 不一样（建议如果不用 SF Symbol，这块也尽量使用 pdf 等矢量图格式）

<img width="806" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/d042f65e-4ccd-4306-99c3-fb5179adbe84">

2023-12-29 02:19 UTC, tisfeng commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
哦哦，看到了。

2023-12-29 02:27 UTC, tisfeng commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
>      NSImage *privacyImage = [NSImage imageNamed:@"toolbar_privacy"]; 

这个是忘记移除了，目前没有用到 toolbar_privacy 图片。

`ez_imageWithSymbolName` 方法内部用到的 imageWithSystemSymbolName 是支持 macOS 11.0，这个没问题吧？

```objc
+ (nullable instancetype)imageWithSystemSymbolName:(NSString *)name accessibilityDescription:(nullable NSString *)description API_AVAILABLE(macos(11.0));
```

2023-12-29 02:40 UTC, Kyle-Ye commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
imageWithSystemSymbolName 这个方法没啥问题，但是 SF 图片分为
- SF 1.0 (macOS 10.15+)
- SF 2.0 (macOS 11+)
- SF 3.0 (macOS 12+)
你用的这个图片资源是 SF 3.0 里的，我上面给你贴出来了

2023-12-29 02:46 UTC, tisfeng commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
我的，真没注意 SF 图片还有这么多类型 😢

请问有什么便捷方式能够将 SF 图片转为正常的 png 图片吗？代码或者工具都行，我不会制作图片，一个个去找 SF 对应的图片有点累。

2023-12-29 02:52 UTC, Kyle-Ye commented on Easydict/NewApp/View/MenuItemView.swift
> +@available(macOS 13, *)
直接在 SF App 里拷贝/导出就可以了呀，不过强烈不建议这样做

png会失真，而且和 SwiftUI.font 等不兼容，会失去很多排版对齐、缩放特性

你需要自定义图片的话建议是转成 SF Symbol

https://developer.apple.com/sf-symbols/

2023-12-29 07:02 UTC, Kyle-Ye commented
@tisfeng 这块还有什么其他建议吗？看下是哪边先合入

2023-12-29 10:04 UTC, tisfeng commented
> @tisfeng 这块还有什么其他建议吗？看下是哪边先合入（要不这个先合，然后你帮忙解决下冲突？）

没什么问题，就是新的菜单项和设置页内容还不完整，直接对外开放不太好，要不我们先在 debug 环境启用，等后面完善了开放？

2023-12-29 10:06 UTC, Kyle-Ye commented
可以呀，现在已经有一个 Beta 开关，默认关闭，需要用户手动开启，所以咱们干脆直接把这个 Beta 开关也在 Debug 才显示吗？

2023-12-29 10:08 UTC, Kyle-Ye commented on Easydict.xcodeproj/project.pbxproj
> +				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG $(inherited)";
之前只给 Clang 在 DEBUG 下定义了 DEBUG，Swift 侧用 #if DEBUG 不会生效，应该是工程建得太早的原因，这里补齐添加了 swiftc 的 DEBUG 定义

2023-12-29 11:32 UTC, tisfeng commented
> 可以呀，不完整是符合预期的，目前没有预期让大部分用户使用。
> 
> 现在已经有一个 Beta 开关，默认关闭，需要用户手动开启才会进入，所以你是想咱们只在 Debug 包里才展示 Beta 开关吗？

不不，这里还是用 #if DEBUG 吧

2023-12-29 11:53 UTC, Kyle-Ye commented
> 不不，这里还是用 #if DEBUG 吧

没太理解你的request change诉求，是希望再所有代码处都用 #if DEBUG 包裹吗？还是在仅 DEBUG 下展示 BETA 开关即可。按照后者修改了下

2023-12-29 12:05 UTC, tisfeng commented
没问题，就是这样，是我没说清楚。

因为目前设置页还未完成，暂时还不想暴露给用户，所以在 DEBUG 环境我们自己测试使用就好。

而 Beta 项主要面向用户测试一些新功能，这些功能也都是完整的。

2023-12-29 12:07 UTC, tisfeng commented
这个我就先合并了，既然有了一部分基础，设置页也相对独立，后面我们就先将设置页的代码都迁移到 Swift/SwiftUI。

2023-12-29 12:08 UTC, tisfeng approved these changes

2023-12-29 12:08 UTC, merged