Niutrans support
tisfeng/Easydict pull request #222
Opened 2023-11-15 02:13 UTC by BigGuang97

初步支持小牛翻译 #211 

APIkey配置方法与DeepL相同：
easydict://writeKeyValue?EZNiuTransAuthKey=xxx

2023-11-15 13:28 UTC, tisfeng commented
你好，请提交 PR 到 dev 分支，这里有说明   https://github.com/tisfeng/Easydict#%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97

2023-11-15 14:16 UTC, tisfeng commented on Easydict/.DS_Store
我记得项目中有 .gitignore，为什么 .DS_Store 文件还会被提交上来？

2023-11-15 14:19 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : ""
这里应该需要一个“小牛翻译”的英文名字，你可以切到英文环境测试一下。

2023-11-15 14:27 UTC, tisfeng commented on Easydict/Feature/Service/Niutrans/EZNiuTransTranslate.m
> +                                                                        EZLanguageHebrew, @"et",
这个语言代码有问题，文档上显示希伯来语是 he，我没有仔细看，麻烦你一一校对一下。

https://niutrans.com/documents/contents/trans_text#languageList

<img width="955" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/a5342978-cb3a-4692-8c0e-acad21a18ea9">

2023-11-15 14:30 UTC, tisfeng commented on Easydict/Feature/Service/Niutrans/EZNiuTransTranslate.m
> +- (EZWebViewTranslator *)webViewTranslator {
这个属性是没必要的，我还看到一些其他与当前功能无关的代码。

如果是因为你不熟悉 objc ，这部份多余的代码稍后我可以帮你去掉。

2023-11-15 14:35 UTC, tisfeng commented on Easydict/App/EZConst.h
> +static NSTimeInterval const EZNetWorkTimeoutInterval = 150.0;
默认设置网络超时时间为 15s，为什么要改这个值？

2023-11-15 14:39 UTC, tisfeng requested changes
请修改代码后，提交 PR 到 dev 分支。

2023-11-15 16:48 UTC, tisfeng commented on Easydict/Feature/Service/Model/EZConstKey.h
> +static NSString *const EZNiuTransAPIKey = @"EZNiuTransAPIKey";
我这里改了一下命名 EZNiuTransAuthKey --> EZNiuTransAPIKey

2023-11-15 17:06 UTC, tisfeng commented on Easydict/Feature/Service/Niutrans/EZNiuTransTranslate.m
> +        @"apikey" : self.apiKey,
Easydict 的最初设计是希望能开箱即用，目前大部份翻译服务也不需要用户手动设置 key，所以暂时还未提供界面方式配置 key （后面重写设置页时会添加配置页面，但还需要一段时间）。

鉴于命令方式配置 key 不太友好，且当前已内置了较多优质的翻译服务，建议可以为 apikey 提供一个默认值，这样既能方便新用户使用，也能提升小牛翻译的竞争力。

2023-11-15 17:16 UTC, tisfeng commented on Easydict/Feature/Service/Niutrans/EZNiuTransTranslate.m
> +        @"apikey" : self.apiKey,
参考这里 [彩云小译](https://github.com/tisfeng/Easydict/pull/218#discussion_r1390128974) 就提供了一个官方的 Token ，当然，为了避免滥用，可以为这个 key 做一些设置，比如限制每日最大免费字符数量。

如果确定了，可以通过邮件发给我，我在应用内简单加密处理一下。

2023-11-16 06:57 UTC, BigGuang97 commented
非常感谢您的建议，我这边第一次使用objc，都是摸索着来。
您提出的这些问题我会做出修改并重新提交。
默认APIkey的问题我们这边讨论一下，邮件与您联系。

2023-11-16 10:14 UTC, tisfeng commented
你好，请关闭这个 PR，将修改后的代码重新提交 PR 到 dev 分支，目前这个 PR 提交到 main 分支，导致有很多冗余的代码变动，不方便 review 代码。

<img width="952" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f6d543d2-5141-47d6-b413-f7561f68cfdf">

2023-11-16 10:14 UTC, closed without merging

2023-11-16 10:16 UTC, tisfeng commented
你可以在本地拉取最新的 dev 分支代码，将你这个 PR 的代码 rebase dev