Niutrans support
tisfeng/Easydict pull request #226
Opened 2023-11-17 02:36 UTC by BigGuang97

#222

2023-11-17 08:57 UTC, tisfeng commented on Podfile.lock
> +PODFILE CHECKSUM: 3e98cd87eb9495431dc2cd105c1571edc8f60360
这里为什么会改动这个文件内容？

2023-11-17 08:58 UTC, tisfeng commented on Pods/AFNetworking/AFNetworking/AFURLResponseSerialization.m
> +    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/javascript", @"text/html", nil];
一般情况，不应该手动修改第三方 Pod 库的，请问你这里修改是为什么？

2023-11-17 09:01 UTC, tisfeng commented on Easydict.xcodeproj/project.pbxproj
> +			developmentRegion = "zh-Hans";
请问这个是在哪里修改的，为什么修改？

Easydict.xcodeproj/project.pbxproj 配置文件不一般不要随便修改。

2023-11-17 09:03 UTC, tisfeng commented on Easydict/App/mul.lproj/Main.xcstrings
> +  "sourceLanguage" : "zh-Hans",
Easydict/App/mul.lproj/Main.xcstrings 这个文件也是，我记得添加一个新服务，好像是不需要修改这个文件的。

2023-11-17 09:07 UTC, tisfeng commented on Pods/Pods.xcodeproj/project.pbxproj
> +				457A6020E71E493D7145A8EC8874C5BB /* PBXTargetDependency */,
这个文件也不应该修改，你是执行了 pod update，或是接受了系统的建议更改提示？

2023-11-17 09:15 UTC, tisfeng commented
@Kyle-Ye 有空帮忙看一下这个 PR，他刚接触 objc，不知道怎么更改了一些配置文件。。

2023-11-20 01:23 UTC, BigGuang97 commented on Pods/AFNetworking/AFNetworking/AFURLResponseSerialization.m
> +    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/javascript", @"text/html", nil];
这个想让AFNetworking 能够接收text/html格式返回数据。

2023-11-20 01:24 UTC, BigGuang97 commented on Pods/AFNetworking/AFNetworking/AFURLResponseSerialization.m
> +    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/javascript", @"text/html", nil];
这个想让AFNetworking 能够接收text/html格式返回数据。

2023-11-20 01:29 UTC, BigGuang97 commented on Pods/Pods.xcodeproj/project.pbxproj
> +				457A6020E71E493D7145A8EC8874C5BB /* PBXTargetDependency */,
确实在过程中执行了pod update

2023-11-20 07:50 UTC, tisfeng commented on Pods/AFNetworking/AFNetworking/AFURLResponseSerialization.m
> +    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/javascript", @"text/html", nil];
不不，不需要改源码，acceptableContentTypes 有对外的接口的，参考这里

https://github.com/tisfeng/Easydict/blob/f6a8db7e418a74d162be4b42a6b08cc6cb7d0053/Easydict/Feature/Service/Youdao/EZYoudaoTranslate.m#L82

2023-11-20 07:55 UTC, Kyle-Ye requested changes
最小改动原则，先回滚下相关的改动吧，只保留 Easydic.xcodeproj 和 Easydic 文件夹以及 README 的改动

@tisfeng 后续合入的时候记得squash merge下，或者 @BigGuang97 你先本地重新整理 commit 后把这个分支 push --force 下

2023-11-20 08:00 UTC, tisfeng commented on Pods/AFNetworking/AFNetworking/AFURLResponseSerialization.m
> +    self.acceptableContentTypes = [NSSet setWithObjects:@"application/json", @"text/json", @"text/javascript", @"text/javascript", @"text/html", nil];
之前我看了这个接口请求，是 JOSN 格式，也没有用到 text/html

2023-11-20 08:11 UTC, tisfeng commented on Pods/Pods.xcodeproj/project.pbxproj
> +				457A6020E71E493D7145A8EC8874C5BB /* PBXTargetDependency */,
@BigGuang97  不需要执行 pod update，你这个 PR 改了太多无关的东西，你重新整理一下。

你这个分支，编译就报错，Niutrans 目录下的文件没有关联到 target

参考这里的编译步骤，你先本地跑起来，然后弄个新的分支，逐步将提交 pick 到新分支。注意不要乱改配置，也不要改无关的文件代码。

 https://github.com/tisfeng/easydict#%E5%BC%80%E5%8F%91%E8%80%85%E6%9E%84%E5%BB%BA

<img width="1707" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/131e33eb-aa83-4294-aa15-3864ae8664d8">

2023-11-20 08:15 UTC, tisfeng commented on Pods/Pods.xcodeproj/project.pbxproj
> +				457A6020E71E493D7145A8EC8874C5BB /* PBXTargetDependency */,
删除 Xcode 中空的 Niutrans，参照下面选项，将外部的 Niutrans 目录拖到 Xcode 的 Service 下面

<img width="956" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0cabdeec-9ad2-4286-ae84-2be3118abd02">


<img width="766" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/9b5ad0ec-eb06-45d8-af0a-827228634d0e">

2023-11-20 08:19 UTC, tisfeng commented on Pods/Pods.xcodeproj/project.pbxproj
> +				457A6020E71E493D7145A8EC8874C5BB /* PBXTargetDependency */,
我帮你加到 target 了，你整理一下代码吧。

2023-11-21 03:49 UTC, tisfeng commented
@BigGuang97 你好，请尽快解决前面提到的问题，如果需要帮助，我这边也可以提供。

2023-11-23 09:11 UTC, tisfeng commented
已在 https://github.com/tisfeng/Easydict/pull/239 合并。

2023-11-23 09:11 UTC, closed without merging