Add TencentService Support
tisfeng/Easydict pull request #240
Opened 2023-11-26 00:01 UTC by Jerry23011

Closes #182

2023-11-26 03:39 UTC, tisfeng commented
今天看了一下，才知道原来我能免费使用 GitHub Copilot，但我根本没有收到过邮件通知，不知道什么时候获得了这个资格，也不知道是哪个项目到达了标准。

很好奇，不确定是不是 Easydict 达标了，请问你有没有获得免费 GitHub Copilot 资格？

<img width="1003" alt="689a71a8dd4937fca8332bebde695f06" src="https://github.com/tisfeng/Easydict/assets/25194972/69f7c158-268e-4733-b3c0-fe31f3c5cff2">

2023-11-26 03:43 UTC, Jerry23011 commented
> 今天看了一下，才知道原来我能免费使用 GitHub Copilot，但我根本没有收到过邮件通知，不知道什么时候获得了这个资格，也不知道是哪个项目到达了标准。
> 
> 很好奇，不确定是不是 Easydict 达标了，请问你有没有获得免费 GitHub Copilot 资格？

貌似是可以的
<img width="527" alt="截屏2023-11-25 19 42 41" src="https://github.com/tisfeng/Easydict/assets/89069957/a5b3737c-60da-452c-a7a1-4cd4121f2c9e">

2023-11-26 03:49 UTC, tisfeng commented
太棒了，请问这个通知是在哪里看到的，你有收到邮件通知吗？

2023-11-26 03:50 UTC, Jerry23011 commented
> 太棒了，请问这个通知是在哪里看到的，你有收到邮件通知吗？

没收到邮件通知，在右侧边栏中点Copilot就可以看到了
<img width="1317" alt="image" src="https://github.com/tisfeng/Easydict/assets/89069957/403eef3f-534d-43e1-81cd-767e0665dd4b">

2023-11-26 03:54 UTC, Jerry23011 commented
不知道 Easydict 是不是属于"popular open source project"了
> GitHub Copilot is free to use for verified students, teachers, and maintainers of popular open source projects."
>
> https://docs.github.com/en/billing/managing-billing-for-github-copilot/about-billing-for-github-copilot

2023-11-26 04:20 UTC, tisfeng commented
看起来应该是 Easydict。

 @choykarl @rainzm 你们有 GitHub Copilot 免费资格吗，另外你们有成为其他流行项目的 maintainer 吗？

2023-11-26 06:52 UTC, Jerry23011 commented
@tisfeng 就差 Request Header 里面的 Authentication 参数了，实在是不知道这个[签名方法v3](https://cloud.tencent.com/document/api/551/30636)为什么要一遍一遍算SHA256和16进制，如果有空的话可以让你看看吗？是在不行就先用[签名v1](https://cloud.tencent.com/document/api/551/15616)

2023-11-26 07:17 UTC, tisfeng commented
等我先发个新版本，晚上再看。

2023-11-27 09:36 UTC, choykarl commented
> 看起来应该是 Easydict。
> 
> @choykarl @rainzm 你们有 GitHub Copilot 免费资格吗，另外你们有成为其他流行项目的 maintainer 吗？

@tisfeng 我一直都在用啊，我以为你们也知道

2023-11-27 09:56 UTC, tisfeng commented
我没注意到，我之前是付费使用 GitHub Copilot，不知道什么时候激活了免费资格，它又不给发邮件通知。。

@choykarl  你记得是什么时候拿到免费资格的吗，我比较好奇这个所谓 “流行开源项目” 标准是什么？

2023-11-27 10:01 UTC, choykarl commented
> 我没注意到，我之前是付费使用 GitHub Copilot，不知道什么时候激活了免费资格，它又不给发邮件通知。。
> 
> @choykarl 你记得是什么时候拿到免费资格的吗，我比较好奇这个所谓 “流行开源项目” 标准是什么？

@tisfeng 我好像进到项目里的时候就可以用，这个发放不知道啥标准，好像跟star也没关系，有的几百star就有，我的几千也没有。

2023-11-28 05:39 UTC, tisfeng commented
这里最好不要使用自动 git pull 方式 merge，会显示多余的提交，建议使用 rebase 方法，保持提交历史简洁。

我电脑默认设置 git pull 就是 rebase：

```bash
git config --global pull.rebase true
```

参考 https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%8F%98%E5%9F%BA

> 在本例中另一种简单的方法是使用 git pull --rebase 命令而不是直接 git pull。 又或者你可以自己手动完成这个过程，先 git fetch，再 git rebase teamone/master。
> 
> 如果你习惯使用 git pull ，同时又希望默认使用选项 --rebase，你可以执行这条语句 git config --global pull.rebase true 来更改 pull.rebase 的默认配置。

<img width="1295" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f2158d06-f16a-4cca-9eb5-171c843f1aae">

2023-11-28 05:42 UTC, Jerry23011 commented
> 这里最好不要使用自动 git pull 方式 merge，会显示多余的提交，建议使用 rebase 方法，保持提交历史简洁。

原来如此，我是纯GUI，回头学习一下CLI

2023-11-28 06:16 UTC, Jerry23011 commented
彻底懵了，@tisfeng 我回头在开一个 branch + PR，这个先放在这，我试验试验

2023-11-28 14:47 UTC, tisfeng commented on Easydict/Feature/Service/Model/EZConstKey.h
> +static NSString *const EZTencentAPIKey = @"EZTencentAPIKey";
这里怎么两个 EZTencentAPIKey，编译不会报错吗

2023-11-28 14:48 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        if from == .simplifiedChinese {
这里需要优化一下，参考彩云小译

https://github.com/tisfeng/Easydict/blob/dev/Easydict/Feature/Service/Caiyun/CaiyunTranslateType.swift#L17

2023-11-28 14:49 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +    var tencentValue: String {
这里也是，和前面的 supportLanguagesDictionary 代码重复，需要优化

https://github.com/tisfeng/Easydict/blob/dev/Easydict/Feature/Service/Caiyun/CaiyunTranslateType.swift#L27

2023-11-28 14:56 UTC, tisfeng commented on Easydict/Feature/Utility/EZLinkParser/EZSchemeParser.m
> +        EZTencentAPIKey,
重复的 EZTencentAPIKey

2023-11-28 17:16 UTC, Jerry23011 commented on Easydict/Feature/Service/Model/EZConstKey.h
> +static NSString *const EZTencentAPIKey = @"EZTencentAPIKey";
解决conflict的时候解决错了

2023-11-29 01:49 UTC, tisfeng commented on Easydict/Feature/Service/Model/EZConstKey.h
> +static NSString *const EZTencentAPIKey = @"EZTencentAPIKey";
我常用 VScode 解决冲突，挺好用的。

2023-11-29 08:05 UTC, Jerry23011 commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        if from == .simplifiedChinese {
已优化

2023-11-29 08:49 UTC, Jerry23011 commented
好像 rebase 成功了 :)

2023-11-29 10:35 UTC, tisfeng commented
可以，这个提交历史就清晰了。

这个签名确实比较麻烦，你可以看一下我之前另一个项目中的腾讯翻译，是用 TS 写的，或者你 github 搜一下其他 Swift 写的

https://github.com/tisfeng/Raycast-extensions/blob/b259e477bef075157476f624c0f783493686183d/extensions/easydict/src/translation/tencent.ts#L42

2023-11-29 13:54 UTC, tisfeng commented on Easydict/App/Assets.xcassets/service-icon/Tencent.imageset/Tencent Translate.png
这个图标不就是 [腾讯翻译君](https://fanyi.qq.com/ ) 的图标吗 ，为什么要改？

2023-11-29 13:55 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
>          "en" : {
腾讯翻译，也添加一个英文名吧

2023-11-29 13:57 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        let orderedDict = MMOrderedDictionary<AnyObject, AnyObject>()
我之前说的是这里和 TencentTranslateType.supportLanguagesDictionary 代码重复了，所以提取放到 TencentTranslateType 里。

2023-11-29 19:30 UTC, Jerry23011 commented on Easydict/App/Assets.xcassets/service-icon/Tencent.imageset/Tencent Translate.png
改回来了，确实是腾讯翻译君的

2023-11-29 19:31 UTC, Jerry23011 commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        let orderedDict = MMOrderedDictionary<AnyObject, AnyObject>()
最新代码已commit

2023-11-29 19:36 UTC, Jerry23011 commented
> 或者你 github 搜一下其他 Swift 写的

原来腾讯官方有demo，但是文档上貌似没提😄
备忘一下：https://github.com/TencentCloud/signature-process-demo/blob/main/signature-v3/swift/signv3.swift

2023-11-30 04:17 UTC, rainzm commented
> 看起来应该是 Easydict。
> 
> @choykarl @rainzm 你们有 GitHub Copilot 免费资格吗，另外你们有成为其他流行项目的 maintainer 吗？

我一直在用的是Codeium

2023-11-30 13:40 UTC, tisfeng commented
试了一下，好像可以跑起来了。 赞 👍

2023-12-01 09:31 UTC, Jerry23011 commented
@tisfeng 进行了一些测试，现在发现了一个问题，就是源语言和目标语言同样时（比如 英语 -> 英语）腾讯和彩云都显示不支持，我看其他服务都是支持的，这个地方需要改一下吗？

2023-12-01 12:41 UTC, tisfeng commented
你是不是又 rebase 冲突了没解决，代码拉下来编译报错

<img width="1706" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/929b280f-7234-41a7-8e46-9d75ca65265e">

2023-12-01 13:02 UTC, tisfeng commented
> @tisfeng 进行了一些测试，现在发现了一个问题，就是源语言和目标语言同样时（比如 英语 -> 英语）腾讯和彩云都显示不支持（TranslateType 中每种语言没包含源语言），我看其他服务都是支持的，这个地方需要改一下吗？

主要是腾讯和彩云翻译的支持类型有点怪，其他服务都是只有支持某些语言，那这些语言之间都可以随便转，这两家还要一个个去辨别。

原则上，如果该服务接口支持源语言和目标语言，那我们也支持，比如腾讯翻译，我试了一下，它是支持，因此你可以加一下这个逻辑。

而彩云小译是不支持的，但是这个错误提示不够友好，稍后我改进一下。

2023-12-01 13:24 UTC, tisfeng requested changes

2023-12-01 13:30 UTC, tisfeng requested changes

2023-12-01 13:30 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        // ************* 步骤 1：拼接规范请求串 *************
这里可以优化一下，把签名部分抽取成一个单独的方法，方便其他调用。

腾讯提供的服务比较多，效果也不错，像语种识别，TTS 和 OCR 都可以支持一下。

2023-12-01 21:18 UTC, Jerry23011 commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        // ************* 步骤 1：拼接规范请求串 *************
已优化

2023-12-01 21:28 UTC, Jerry23011 commented
> 腾讯提供的服务比较多，效果也不错，像语种识别，TTS 和 OCR 都可以支持一下。

[语种识别](https://cloud.tencent.com/document/product/551/15620)和 [OCR](https://cloud.tencent.com/document/product/551/17232) 我回头就看看，但是 [TTS](https://cloud.tencent.com/document/product/1073/34112) 貌似额度有限👇
 > 免费额度如下：
>
> 语音合成免费额度为800万字符，仅支持通用语音合成接口，暂不支持长文本语音合成接口。免费资源包自您领取成功后起三个月内有效，一个账号只能领取一次。

2023-12-02 01:58 UTC, tisfeng commented
行，那 TTS 就不加了，图片翻译可以加一下，这个额度完全够用了。

https://cloud.tencent.com/document/product/551/35017

> 文本翻译的每月免费额度为5百万字符。
图片翻译的每月免费额度为1万次调用。
语音翻译的每月免费额度为1万次调用。
文件翻译无每月免费额度。
免费额度每月1日0点重置。

另外 OCR 和图片翻译不一样，OCR 在 [文字识别](https://cloud.tencent.com/document/product/866) 模块下面，免费额度也不错，苹果系统 OCR 支持的语种有限，这个可以考虑作为备用选项。

https://cloud.tencent.com/document/product/866/35945

> 通用文字识别、卡证文字识别、票据单据识别、特定场景识别、智能结构化识别、文本图像增强、二维码和条形码识别服务开通后即可享受1,000次/月的免费调用额度，以免费资源包的形式在每个月1号自动发放到您的腾讯云账号中

> 本接口支持图像整体文字的检测和识别。可以识别中文、英文、中英文、日语、韩语、西班牙语、法语、德语、葡萄牙语、越南语、马来语、俄语、意大利语、荷兰语、瑞典语、芬兰语、丹麦语、挪威语、匈牙利语、泰语，阿拉伯语20种语言，且各种语言均支持与英文混合的文字识别。

2023-12-02 05:05 UTC, tisfeng commented
> 你是不是又 rebase 冲突了没解决，代码拉下来编译报错
> 
> <img alt="image" width="1706" src="https://private-user-images.githubusercontent.com/25194972/287266539-929b280f-7234-41a7-8e46-9d75ca65265e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0OTM3ODcsIm5iZiI6MTcwMTQ5MzQ4NywicGF0aCI6Ii8yNTE5NDk3Mi8yODcyNjY1MzktOTI5YjI4MGYtNzIzNC00MWE3LThlNDYtOWQ3NWNhNjUyNjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDA1MDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlM2M5NWM3ZThhM2VhYzBhNGMzNjU0ODcwMTM2YjNmNWZkZTFlOTdiNmNkMGZhZDMyMDQwMzRjNDlhMTUxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1c638qECquhDLqItQUPaXYLW8Dqg4Uj7ohUthvyV3kY">

另外，昨天我提交一个修复 commit 5c8c85d3 ，怎么这个记录不见了？

<img width="1706" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f59a705e-31d6-4b07-9054-4d3fa103ba68">

2023-12-02 05:20 UTC, tisfeng requested changes

2023-12-02 05:20 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        func headerAuth() -> (authorization: String, ct: String) {
这里签名相关的方法，不要放到 translate 方法里面，能移出去的都移出去，保持 translate 简洁。

2023-12-02 05:25 UTC, Jerry23011 commented
> 另外，昨天我提交一个修复 commit [5c8c85d](https://github.com/tisfeng/Easydict/commit/5c8c85d3edefe033e4e728ed6d21f073052b21d6) ，怎么这个记录不见了？

我也很奇怪，因为我代码拉下来之后一 rebase 那个记录就不见了，我用的是 GitHub Desktop 自带的 rebase

2023-12-02 05:30 UTC, choykarl commented
> 不对劲，你的 git 操作有问题，怎么每次都更改了之前的提交历史时间，感觉是在重写？

我只执行rebase也会把所有的commit时间都变成当前的，后来我该用git rebase --committer-date-is-author-date这个就会保留原始时间。

还有是不是rebase完只能强推啊，感觉很危险。。。

2023-12-02 06:22 UTC, Jerry23011 commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        func headerAuth() -> (authorization: String, ct: String) {
试了一下，发现签名里需要拼接+计算 parameter 的值，parameter 挪出去单独用一个方法就接收不到 text 和 from/to 了，不知道这个应该怎么办

2023-12-02 08:27 UTC, tisfeng commented
> > 另外，昨天我提交一个修复 commit [5c8c85d](https://github.com/tisfeng/Easydict/commit/5c8c85d3edefe033e4e728ed6d21f073052b21d6) ，怎么这个记录不见了？
> 
> 我也很奇怪，因为我代码拉下来之后一 rebase 那个记录就不见了，我用的是 GitHub Desktop 自带的 rebase

我 git 操作一般不用 GUI，都是直接终端命令行，SourceTree 也是用来看历史的，不确定其他 GUI 的 rebase 到底是怎么执行的。

2023-12-02 08:29 UTC, tisfeng commented
> > 不对劲，你的 git 操作有问题，怎么每次都更改了之前的提交历史时间，感觉是在重写？
> 
> 我执行git rebase也会把所有的commit时间都变成当前的，后来我改用git rebase --committer-date-is-author-date这个就会保留原始时间。
> 
> 还有是不是rebase完只能强推啊，感觉很危险。。。

怎么会这样，你是使用命令 git pull --rebase 会导致修改提交时间？

我这边这样用没有问题，rebase 后可以正常推送，不需要 -f 强推。

2023-12-02 08:34 UTC, choykarl commented
> > > 不对劲，你的 git 操作有问题，怎么每次都更改了之前的提交历史时间，感觉是在重写？
> > 
> > 
> > 我执行git rebase也会把所有的commit时间都变成当前的，后来我改用git rebase --committer-date-is-author-date这个就会保留原始时间。
> > 还有是不是rebase完只能强推啊，感觉很危险。。。
> 
> 怎么会这样，你是使用命令 git pull --rebase 会导致修改提交时间？
> 
> 我这边这样用没有问题，rebase 后可以正常推送，不需要 -f 强推。

git pull --rebase不会，git rebase xxxbranch会

2023-12-02 11:04 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        func headerAuth() -> (authorization: String, ct: String) {
直接将 parameter 当作参数就可以，我简单优化了一下签名函数，后面你添加其他 API 的时候再根据情况修改。

2023-12-02 11:11 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        .japanese: [.simplifiedChinese, .traditionalChinese, .english, .japanese, .korean],
这里不要这样写，太笨了，你直接按照文档写就可以。

.japanese: [.simplifiedChinese, .english, .korean],

> ja（日语）：zh（中文）、en（英语）、ko（韩语）

https://cloud.tencent.com/document/api/551/15619

2023-12-02 11:15 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        .japanese: [.simplifiedChinese, .traditionalChinese, .english, .japanese, .korean],
这里的 supportedTypes 是为了方便 transType 调用，如果是为了处理源语言和目标语言一样的情况，你直接在 transType 中加个判断条件就可以了。

2023-12-02 11:17 UTC, tisfeng requested changes

2023-12-02 11:23 UTC, tisfeng commented
> > > > 不对劲，你的 git 操作有问题，怎么每次都更改了之前的提交历史时间，感觉是在重写？
> > > 
> > > 
> > > 我执行git rebase也会把所有的commit时间都变成当前的，后来我改用git rebase --committer-date-is-author-date这个就会保留原始时间。
> > > 还有是不是rebase完只能强推啊，感觉很危险。。。
> > 
> > 
> > 怎么会这样，你是使用命令 git pull --rebase 会导致修改提交时间？
> > 我这边这样用没有问题，rebase 后可以正常推送，不需要 -f 强推。
> 
> git pull --rebase不会，git rebase xxxbranch会

很奇怪，我一直都是这样操作的，比如我这边添加一个新提交，执行完 git rebase dev 再 git push，也不会更改提交历史时间的。

<img width="1704" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0d636e15-241d-4d58-9642-ecf3f77e1839">

2023-12-02 11:29 UTC, tisfeng commented
git 我也不是很精通，一些配置和命令太复杂了，我也不清楚你们的开发环境，这个只能你们自己测试，找找问题在哪。

如果实在不行，那就不要 git rebase dev，这个只是为了减少代码冲突，大不了后面我手动合并解决。

2023-12-02 11:35 UTC, tisfeng commented
才发现，你们一直在强推，这肯定哪个地方操作有问题 🤔

<img width="1024" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/893f3c87-8ae7-4a42-8276-27682086bb79">


我这边 review 修改代码时，这些提交都可以正常 push 的。

<img width="970" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/92573578-fe08-4f8e-b4d1-3a00ef5719b7">

2023-12-02 12:10 UTC, choykarl commented
@tisfeng 是不是因为你一直在当前项目的dev分支的原因，而我们是fork出来的项目，然后从这个项目dev分支进行rebase。你试一下开一个分支出来进行操作呢。

2023-12-02 12:23 UTC, choykarl commented
我刚在本地建了个测试的git项目试了下也是好的，不会改变时间。。。

2023-12-02 13:41 UTC, tisfeng commented
> @tisfeng 是不是因为你一直在当前项目的dev分支的原因，而我们是fork出来的项目，然后从这个项目dev分支进行rebase。你试一下开一个分支出来进行操作呢。
> 
> 例如从dev的64a3b3ff这次commit切出一个分支来，然后在新分支隔一分钟commit一次，模拟几次commit，再然在这个新分支git rebase dev。你看下rebase完以后，你之前隔一分钟commit一次的记录会不会都变成新的？

试了一下，还真是，之前我都只是直接推自己的 dev 分支就没发现这个问题 😓

仔细看了一下，根据这里的建议，推到远程的分支，就最好不要 git rebase 了。

https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%8F%98%E5%9F%BA

<img width="730" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/cbb68ca3-b67d-4ca1-8426-a3438789d779">

2023-12-02 13:51 UTC, choykarl commented
> 仔细看了一下，根据这里的建议，推到远程的分支，就最好不要 git rebase 了。

我之前的团队有个规矩是，如果多人在同一个分支开发，那么pull的时候要使用rebase，这样整个提交记录看起来是连续的，也不会有我们这样时间被重置的问题。但是开发完将这个分支合并到发布分支的时候，就会使用merge。

2023-12-02 19:59 UTC, Jerry23011 commented
> 还有是不是rebase完只能强推啊，感觉很危险。。。

确实很危险，@tisfeng 的commit又没了😅
还好 stash 了一下。。

2023-12-02 20:06 UTC, Jerry23011 commented
我在 GitHub Desktop 上显示的 commit 时间貌似是原来的，不知道为什么推上来之后就改了
<img width="300" alt="截屏2023-12-02 12 05 44" src="https://github.com/tisfeng/Easydict/assets/89069957/b37f68d6-c164-4499-9428-615b75454b1c">

2023-12-02 20:30 UTC, Jerry23011 commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        .japanese: [.simplifiedChinese, .traditionalChinese, .english, .japanese, .korean],
CV了一下彩云，现在完全按照文档，支持源语言和目标语言相同，支持简/繁自动转换

2023-12-03 01:59 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentService.swift
> +        let endpoint = "https://tmt.tencentcloudapi.com"
我是直接从这里 https://github.com/TencentCloud/signature-process-demo/blob/main/signature-v3/swift/signv3.swift#L20 复制过来的，测试能跑通，没注意到这点。。

2023-12-03 02:08 UTC, tisfeng commented on Easydict/Feature/Service/Tencent/TencentTranslateType.swift
> +        .japanese: [.simplifiedChinese, .traditionalChinese, .english, .japanese, .korean],
这种文档相关的信息，应该把链接也加上去，方便对照参考。

2023-12-03 03:19 UTC, tisfeng commented
> > 另外，建议去 https://gravatar.com/ 设置一下个人头像，你这个头像不好识别。
> 
> 设置好了，我在 SourceTree 里面应该怎么刷新才能看到最新设置的头像呢
> 
> 按照[这个](https://takoyaking.hatenablog.com/entry/gravatar)试了一下，还是看不到，好奇怪

我也不知道怎么触发刷新，可能本地应用有缓存，没看到在哪里清除，过一会应该会好的。

2023-12-03 03:27 UTC, Jerry23011 commented
> 这个邮箱要是你 Gravatar 的邮箱，另外要开启显示 Gravatar 头像选项。

糟糕，我所有的 commit 都是 GitHub 的 89069957+Jerry23011@users.noreply.github.com

Gravatar 需要注册邮箱是这个才能用，我不能用这个注册，因为它收不了邮件
> The email address you use for your account on the other site must be one of the email addresses that is registered to your Gravatar account.

2023-12-03 03:33 UTC, tisfeng commented
那我也不清楚了，反正我一般用的邮箱都是相同的这一个。

你自己看看怎么弄，实在不行就算了吧。

2023-12-03 03:46 UTC, tisfeng commented
可以，有个头像看起来清晰一点。

要改的话也可以，只是麻烦一些，要用 git filter-branch 修改提交历史， 参考之前 @choykarl 修改邮箱  https://github.com/tisfeng/Easydict/pull/161#issuecomment-1680655857

2023-12-03 04:15 UTC, tisfeng commented
你这也是生猛，一上来就执行这么危险的操作，你可以先本地弄个仓库测试一下，至少也别直接推上来啊

2023-12-03 04:15 UTC, Jerry23011 commented
😭

2023-12-03 04:16 UTC, Jerry23011 commented
实在不行，我再开一个PR，把代码都手动弄过去。L O L

2023-12-03 04:16 UTC, tisfeng commented
看一下能不能撤回，用 git reflog 看一下操作历史

2023-12-03 04:17 UTC, Jerry23011 commented
这就试试

2023-12-03 04:17 UTC, tisfeng commented
另外，这种和 PR 无关的操作，不要放一起提交，应该单独 PR

2023-12-03 04:18 UTC, Jerry23011 commented
> 另外，这种和 PR 无关的操作，不要放一起提交，应该单独 PR

收到🫡

2023-12-03 05:46 UTC, Jerry23011 commented
> 看一下能不能撤回，用 git reflog 看一下操作历史

撤回了，再也不敢不测试就瞎 push 了 :)

2023-12-03 07:34 UTC, tisfeng commented
本地怎么测试操作都行，只是推送前一定要注意提交的内容，也要确保代码能编译运行。

2023-12-03 09:47 UTC, tisfeng commented
试了一下，虽然文档上没写，但发现腾讯翻译是支持繁体中文的，只要目标语言支持简体中文的都支持繁体中文。

2023-12-11 13:37 UTC, tisfeng commented
这个看起来没什么问题，我就先合并了，游离主分支太久不好，也不方便测试。

后面如果没问题，这周末会发一个新版本。

2023-12-11 13:40 UTC, tisfeng commented
> 行，那 TTS 就不加了，图片翻译可以加一下，这个额度完全够用了。
> 
> https://cloud.tencent.com/document/product/551/35017
> 
> > 文本翻译的每月免费额度为5百万字符。
> > 图片翻译的每月免费额度为1万次调用。
> > 语音翻译的每月免费额度为1万次调用。
> > 文件翻译无每月免费额度。
> > 免费额度每月1日0点重置。
> 
> 另外 OCR 和图片翻译不一样，OCR 在 [文字识别](https://cloud.tencent.com/document/product/866) 模块下面，免费额度也不错，苹果系统 OCR 支持的语种有限，这个可以考虑作为备用选项。
> 
> https://cloud.tencent.com/document/product/866/35945
> 
> > 通用文字识别、卡证文字识别、票据单据识别、特定场景识别、智能结构化识别、文本图像增强、二维码和条形码识别服务开通后即可享受1,000次/月的免费调用额度，以免费资源包的形式在每个月1号自动发放到您的腾讯云账号中
> 
> > 本接口支持图像整体文字的检测和识别。可以识别中文、英文、中英文、日语、韩语、西班牙语、法语、德语、葡萄牙语、越南语、马来语、俄语、意大利语、荷兰语、瑞典语、芬兰语、丹麦语、挪威语、匈牙利语、泰语，阿拉伯语20种语言，且各种语言均支持与英文混合的文字识别。

至于后面的图片翻译和 OCR，你可以另外提 PR。

2023-12-11 13:40 UTC, tisfeng approved these changes

2023-12-11 13:46 UTC, merged

2023-12-11 17:11 UTC, Jerry23011 commented
OK，最近一直没来得及看这个