Add bing dict support
tisfeng/Easydict pull request #243
Opened 2023-11-27 09:38 UTC by choykarl

When translating Chinese using English words, use bing dict api

2023-11-27 09:56 UTC, choykarl commented
本来是用swift写了个从网页获取token去请求翻译的类，后来从app上抓到了接口，就改用接口了，因为不需要新增类，就没用swift了。。。

2023-11-27 11:43 UTC, choykarl commented
> #### ⚠️ GitGuardian has uncovered 8 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

这个的意思是说在[70620b1]( https://github.com/tisfeng/Easydict/commit/70620b19e994bb83f96a3510a94d03630d9611f1)这个commit的`appcast.xml`这个文件里有个hardcoded secrets？

2023-11-27 15:45 UTC, tisfeng commented
我本地用 GitGuardian 的工具本地扫了一下，这里应该是提示 edSignature 值泄漏，可能是有人把这个项目放到 Microsoft Azure 上？而 GitGuardian 会自动扫描上面的 key 泄漏情况。

主要是你这里合并了 dev，显示提交时间落后，GitGuardian 就以为 key 泄漏了。。

下次不要 merge 用 rebase 试试。

<img width="1709" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/4b54156e-887b-4457-ac7f-ad7df9a14e7e">

2023-11-27 15:51 UTC, choykarl commented
> 下次不要 merge 用 rebase 试试。

@tisfeng  那这个现在影响合并么

2023-11-27 16:02 UTC, tisfeng commented
应该不影响。

你把这个分支 git rebase dev，然后再推上来试试。

2023-11-27 16:03 UTC, tisfeng commented
这个词典接口是不是有问题，我看返回内容是空的
```
(lldb) po responseObject
{
  "_type" : "DictionaryWords",
  "value" : [
  ]
}
query error: Error Domain=com.izual.Easydict Code=1 "查询失败, 接口异常: bing dict translate value is empty" UserInfo={NSLocalizedDescription=查询失败, 接口异常: bing dict translate value is empty}
```
<img width="452" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6c790735-a47d-4084-8e58-773234a00c5d">

2023-11-27 16:06 UTC, tisfeng commented
<img width="1079" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/98a368a1-c43f-4d92-9166-0d6e2ee06034">

2023-11-27 16:09 UTC, tisfeng commented
不不不，你这样把彩云那个加进来，看起来更乱了。

你干脆基于最新的 dev 另外弄个分支，把你这个 PR 的提交弄过去，重写开个 PR。

2023-11-27 16:12 UTC, tisfeng commented
每次提交前，建议拉取最新的分支 rebase 一下，有冲突的话本地先解决一下，方便后续的 PR review 以及合并。

2023-11-27 16:21 UTC, choykarl commented
@tisfeng 现在是ok的了吧

2023-11-27 16:34 UTC, choykarl commented
> <img alt="image" width="1079" src="https://private-user-images.githubusercontent.com/25194972/285934061-98a368a1-c43f-4d92-9166-0d6e2ee06034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDI3MjEsIm5iZiI6MTcwMTEwMjQyMSwicGF0aCI6Ii8yNTE5NDk3Mi8yODU5MzQwNjEtOThhMzY4YTEtYzQzZi00ZDkyLTkxNjYtMGQ2ZTJlZTA2MDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2MjcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNGU5MmU3MjZjZTRmZjg1MGI4ZjFhM2JlYWY2NWM5ODA4ODE1N2M3ODZiZjU0ZmY4Mjg2ZGEzNDAwZTJhZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.owCTwKwXOPHp7v7mWj6IU0EdD3XyXOAXYKvJMn1I8xg">

@tisfeng 你这是不是台湾节点，我刚才试了下，我这边就走台湾节点有问题，bingdict网站都打不开，切了几个其他地区的就好使。。。

2023-11-28 04:43 UTC, tisfeng commented
代码 rebase 后没什么问题了。

Bing 的接口有点奇怪，之前我用 [Bing 画图](https://www.bing.com/images/create) 就发现了，它对某些 IP 有限制，我自建的 Vultr 美国两个 IP 都用不了，而 Oracle 的美国节点可以用，所以我就设置规则 *.bing.com 都走 Oracle 节点。

直到今天发现这个节点又用不了 Bing 词典接口，换了另一个节点接口正常。。这个真有点复杂，可能是 IP 被污染了 😓

2023-11-28 05:10 UTC, tisfeng commented
可以。

> 我稍后可以加一下如果dict查询失败，还走之前的translate接口。

跳转网页的链接 wordLink 也改一下，如果查词典，就走这个 https://www.bing.com/dict/search?q=good

这里词组显示优化一下，元数据不动，显示的时候最多显示 5 条

<img width="536" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ec983fbc-03a1-45b2-bf9c-715064484c0c">

2023-11-28 05:15 UTC, tisfeng commented
另外，添加一下 Coll. 搭配 和 Antonym 反义词，尽量和网页版查询显示保持一致。

<img width="875" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f6a79dc3-32a3-477b-9781-175a15e2c226">
<img width="1179" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/b7121bd8-4e43-455e-9722-3349cbfc3332">

2023-11-28 05:37 UTC, choykarl commented
我们现在没有专门的对象展示这两个吧。

2023-11-28 05:59 UTC, tisfeng commented
> 我们现在没有专门的对象展示这两个吧。

如果目前的控件布局不好显示的话，你就参照这个，在 EZTranslateWordResult 里面加字段，然后在 EZWordResultView 根据字段添加控件显示。

<img width="451" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/02c525be-8297-4979-a1bd-163d96916c23">

2023-11-29 09:22 UTC, choykarl commented
> 然后在 EZWordResultView 根据字段添加控件显示。

设计成这样？
<img width="463" alt="image" src="https://github.com/tisfeng/Easydict/assets/12951859/500cbd83-7544-49e0-83b1-fc450aa48bbd">

2023-11-29 10:23 UTC, tisfeng commented
很棒，可以稍微优化一下，把同义词、反义词放到单词的时态和形式下面，另外每个词组最多显示 5 个，尽量和 Bing 词典网页端保持一致。

<img width="647" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/3ab4fc72-8961-4fd6-806d-6b6db68cc369">

2023-11-29 11:51 UTC, tisfeng commented
词性部份，网页上除了 Web 其他都是缩写，所以都后面都有个点 . ，你这里也同步一下。

由于 `EZBlueTextButton` 边框留白较多，因此上下间距可以调小一点，5 就可以了。

<img width="1278" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d4ce4b2a-d5e7-4135-8aa9-3c3f96accad4">

2023-11-29 13:41 UTC, tisfeng requested changes

2023-11-29 13:41 UTC, tisfeng commented on Easydict/Feature/ViewController/View/WordResultView/EZWordResultView.m
> +            *height += kVerticalPadding_8;
```suggestion
            CGFloat topOffset = 5;
            make.top.equalTo(rtnView.mas_bottom).offset(topOffset);
            *height += topOffset;
```

2023-11-29 15:07 UTC, tisfeng commented on Easydict/Feature/ViewController/View/WordResultView/EZWordResultView.m
> +            *height += kVerticalPadding_8;
这种建议修改代码，如果接受的话，只需要点击 `Commit suggestion` ，Review 很好用的。

<img width="973" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/1df319da-4503-4f75-bafe-e83bc61493f6">

2023-11-29 15:42 UTC, choykarl commented
> 词性部份，网页上除了 Web 其他都是缩写，所以都后面都有个点 . ，你这里也同步一下。

我新增了一些标准的词性，但是有一些词性不是标准的，所以加了个如果part是英文就直接在后面加个点的逻辑。你可以确认下这样是否合理。

2023-11-29 16:21 UTC, tisfeng commented
可以，这里暂时就这样，这种奇怪的 part 应该也不多。 常规的，或是需要特殊处理的，还是用词典映射。

2023-11-29 16:43 UTC, choykarl commented
> 可以，这里暂时就这样，这种奇怪的 part 应该也不多。 常规的，或是需要特殊处理的，还是用词典映射。

ok，目前问题貌似改玩了，麻烦继续review吧。

2023-11-30 12:31 UTC, tisfeng commented
重构优化了一下 `NSString *getPartAbbreviation(NSString *part)` 方法，顺便复习了英语单词的词性种类，Bing 词典这点做得不错，其他词典都没有这么详细 😃

你看一下还有没有地方需要改的，没问题的话，这个周末就和彩云小译一起发个新版本。

2023-12-02 13:43 UTC, tisfeng requested changes

2023-12-02 13:58 UTC, choykarl commented on Easydict/Feature/Service/Model/EZQueryResult.m
> +    if (part.length == 0) {
<img width="1114" alt="image" src="https://github.com/tisfeng/Easydict/assets/12951859/40741dc0-0b98-44f3-b959-3ae5a056ea1e">

我昨天碰到了。

2023-12-02 14:35 UTC, tisfeng commented
优化了一下布局显示，让组间上下间距更小，显示更紧凑。

<img width="451" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/38c40b17-e60e-40e0-bdb2-ba5572e12c73">

2023-12-03 13:15 UTC, tisfeng commented
[2.2.0](https://github.com/tisfeng/Easydict/releases/tag/2.2.0) 版本已发布，看一下这个 PR 还有没有问题，合并后下周可以发一个新版。

2023-12-04 14:49 UTC, tisfeng approved these changes

2023-12-04 14:50 UTC, merged