[WIP]feat: add double click modifier as shortcut
tisfeng/Easydict pull request #277
Opened 2023-12-26 14:17 UTC by AkaShark

closed [#220 ]

2023-12-26 14:47 UTC, AkaShark commented
wait for testing

2023-12-27 04:21 UTC, AkaShark commented
> wait for testing
finished test
double-click the modifier key as a shortcut, such as double-click cmd/option/control/shift
@tisfeng

2023-12-27 04:21 UTC, AkaShark commented
> wait for testing

finished test
double-click the modifier key as a shortcut, such as double-click cmd/option/control/shift
@tisfeng

2023-12-27 04:23 UTC, AkaShark commented
closed #154

2023-12-27 14:22 UTC, tisfeng commented
没想到你直接去改源码了，这还真是一种方式，很棒！

2023-12-27 14:29 UTC, tisfeng commented
发现两个小问题：

-  有警告没处理
- 这种特殊双击快捷键触发查询窗口时，需要隐藏查询图标

<img width="1091" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/06197aa3-56d2-496b-bcfa-ad0e164ee90d">

<img width="741" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/aa1f3796-87c2-4869-9285-2f61e386df03">

2023-12-27 14:38 UTC, tisfeng commented
双击快捷键有点复杂，别的应用触发不好判断，因此你只需要处理一下 Easydict 自身的触发就好。

> 这种特殊双击快捷键触发查询窗口时，需要隐藏查询图标

2023-12-27 14:40 UTC, tisfeng commented
快捷键显示查询窗口，好像有点问题，有时候不能正常触发，这个我稍后修复一下。

2023-12-27 14:41 UTC, AkaShark commented
> 没想到你直接去改源码了，这还真是一种方式，很棒！

属于曲线救国了😂，等后续我们有规划迁移Swift的话可以再去考虑怎么维护，毕竟MAShortcut已经不维护了

2023-12-27 14:42 UTC, AkaShark commented
> 双击快捷键有点复杂，别的应用触发不好判断，因此你只需要处理一下 Easydict 自身的触发就好。
> 
> > 这种特殊双击快捷键触发查询窗口时，需要隐藏查询图标

这个别的应用出发不好判断是指我正常操作出发双击么？我在代码里面判断是连续点击0.3s内作为一个完成的操作。

2023-12-27 14:44 UTC, AkaShark commented
> 快捷键显示查询窗口，好像有点问题，有时候不能正常触发，这个我稍后修复一下。

这个也没太理解，是啥场景下呀

2023-12-27 14:48 UTC, tisfeng commented
> > 快捷键显示查询窗口，好像有点问题，有时候不能正常触发，这个我稍后修复一下。
> 
> 这个也没太理解，是啥场景下呀

这个是之前遗留的一个问题，例如默认 Cmd+a 显示查询窗口，再按一次会关闭窗口，再次 Cmd+a 却没有反应，这个有问题。

2023-12-27 15:11 UTC, tisfeng commented
不是，这个问题触发条件比较怪，需要打开显示主窗口。

<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d2daf158-982b-433e-b576-d6e84dda2667">

2023-12-27 15:16 UTC, tisfeng commented
因为发现显示主窗口会导致一些问题，所以目前默认隐藏了主窗口。

主要的问题是，如果显示主窗口，在唤起其他查询窗口时，也会将主窗口显示在前台，感觉会很怪。

我对窗口处理不是很了解，不知道如何解决，就干脆隐藏了。如果你熟悉这块，可以帮忙看一下。

2023-12-27 15:28 UTC, AkaShark commented
我也是刚接触MacOS开发，也不太熟，但是我理解啦你说的”快捷键显示查询窗口，好像有点问题，有时候不能正常触发“，但是对于https://github.com/tisfeng/Easydict/pull/277#issuecomment-1870397735这个comment不是很懂，我测试了下在不勾选主窗口选项后确实存在不能正常出发的情况，这个明天我在研究研究。

2023-12-28 02:47 UTC, tisfeng requested changes

2023-12-28 02:47 UTC, tisfeng commented on Easydict/Feature/Shortcut/EZShortcut.m
> +        [windowManager.popButtonWindow close];
这里可以优化一下，写个方法包装 `[[MASShortcutBinder sharedBinder] bindShortcutWithDefaultsKey:EZInputShortcutKey toAction:`

避免每个地方都需要手动调用 `[windowManager.popButtonWindow close];`，后续可能还会有其他快捷键。

2023-12-29 13:03 UTC, tisfeng commented
你好，我邀请你加入一起开发了。

<img width="830" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/96dc65ee-82e1-4d9a-a2b5-4141715497b1">

2023-12-29 14:05 UTC, AkaShark commented
okay

2023-12-29 14:07 UTC, AkaShark commented on Easydict/Feature/Shortcut/EZShortcut.m
> +        [windowManager.popButtonWindow close];
got it !

2023-12-30 01:29 UTC, tisfeng commented
这个还有问题吗？

2023-12-30 03:26 UTC, AkaShark commented
> 不是，这个问题触发条件比较怪，需要打开显示主窗口。
> 
> <img alt="image" width="617" src="https://private-user-images.githubusercontent.com/25194972/293055053-d2daf158-982b-433e-b576-d6e84dda2667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDcwMjQsIm5iZiI6MTcwMzkwNjcyNCwicGF0aCI6Ii8yNTE5NDk3Mi8yOTMwNTUwNTMtZDJkYWYxNTgtOTgyYi00MzNlLWI1NzYtZDZlODRkZGEyNjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAzMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NDk2NDQyNTMwZmQ1N2JiY2NhYWFiZmJlMTVjMzk2NzAwOGYxZmFmMjhjMGQzNWU2YWE0ZWI5ZDAyYmFiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVWR7Vaebx_4gB7p3zhAi0l_96dQsGWXQ9DAk7RVCto">

不勾选这个主窗口会有快捷键第二次不生效的情况，这个我今天修复下，预计今晚上可以搞定

2023-12-30 03:28 UTC, tisfeng commented
ok

2023-12-30 10:03 UTC, AkaShark commented
我发现默认开启
![CleanShot 2023-12-30 at 18 00 33@2x](https://github.com/tisfeng/Easydict/assets/26460192/59b1c4da-0ee9-4f12-a04b-17b6ed478b91)
主窗口后(不关闭)，用户触发快捷键第一次表现是符合预期的，第二次触发快捷键没有反应，这是由于
![CleanShot 2023-12-30 at 17 59 55@2x](https://github.com/tisfeng/Easydict/assets/26460192/c1ef8fd7-ebdb-432e-b764-18a09e9264d9)
在主窗口没有关闭的情况下，第二次触发快捷键依然是会进这个if导致第二次触发快捷键没反应，这时关闭主窗口后表现正常，但是我没太看明白这是为啥么。。

2023-12-30 10:05 UTC, AkaShark commented
> 我发现默认开启 ![CleanShot 2023-12-30 at 18 00 33@2x](https://private-user-images.githubusercontent.com/26460192/293454329-59b1c4da-0ee9-4f12-a04b-17b6ed478b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzA5ODcsIm5iZiI6MTcwMzkzMDY4NywicGF0aCI6Ii8yNjQ2MDE5Mi8yOTM0NTQzMjktNTliMWM0ZGEtMGVlOS00ZjEyLWEwNGItMTdiNmVkNDc4YjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEwMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZDNiYWI1Njk1YjNkNGI0YzdhODM3MTU5ZTgxNjQ5MTEzZjVhYWJmYjJhODE0ZjQxNWQwNGJiOTMwODA0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BSR80hOkcaFDWsEI2K8dxsaKVesFhwNRPzlMUYLGWVU) 主窗口后(不关闭)，用户触发快捷键第一次表现是符合预期的，第二次触发快捷键没有反应，这是由于 ![CleanShot 2023-12-30 at 17 59 55@2x](https://private-user-images.githubusercontent.com/26460192/293454382-c1ef8fd7-ebdb-432e-b764-18a09e9264d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzA5ODcsIm5iZiI6MTcwMzkzMDY4NywicGF0aCI6Ii8yNjQ2MDE5Mi8yOTM0NTQzODItYzFlZjhmZDctZWJkYi00MzJlLWI3NjQtMThhMDllOTI2NGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEwMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YmQ5NGIwNzJjNTRhOWE5OTNlZmM4MjBkNTMwYWE3MzVmODk5M2E1N2UwMTg5NTZhNmI1ZTAwNWI4ZTY0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JZ9gL4JQ54fvSKhw3mkz9Rufxs5g6rfZW82GRu4sUXY) 在主窗口没有关闭的情况下，第二次触发快捷键依然是会进这个if导致第二次触发快捷键没反应，这时关闭主窗口后表现正常，但是我没太看明白这是为啥么。。

看起来好像是窗口的问题，解决方案倒是比较简单，可以直接在closeFloatingWindow中关闭掉主窗口

2023-12-30 10:52 UTC, tisfeng commented
不不，我之前简单看了一下，好像是开启显示主窗口后，显示并关闭悬浮窗口后，floatingWindowType 这个值计算不正确导致。

如果你不方便解决，可以先放一下，这问题和这个 PR 关系也不大，后面我来看也行。

2023-12-30 13:42 UTC, AkaShark commented
> 不不，我之前简单看了一下，好像是开启显示主窗口后，显示并关闭悬浮窗口后，floatingWindowType 这个值计算不正确导致。
> 
> 如果你不方便解决，可以先放一下，这问题和这个 PR 关系也不大，后面我来看也行。

okay 我又debug了下发现如果把主窗口放在另一个屏幕上，使用快捷键关不掉呼出来的窗口(比如mini)。。。我先直接在触发除主窗口之外的窗口关闭掉主窗口
![CleanShot 2023-12-30 at 21 40 52@2x](https://github.com/tisfeng/Easydict/assets/26460192/9626f8f1-1e6f-492a-9a9f-cf1617fe2843)
这样看起来能暂时的解决这个问题

2023-12-30 13:47 UTC, AkaShark commented
感觉这个问题是由于
![CleanShot 2023-12-30 at 21 43 21@2x](https://github.com/tisfeng/Easydict/assets/26460192/07c6e77a-0031-4fa6-ac83-ecd14f349990)
这个代理回调多次，然后关闭窗口后再获取floatingWindowType发现这个值被改掉了
![CleanShot 2023-12-30 at 21 34 04@2x](https://github.com/tisfeng/Easydict/assets/26460192/ed398654-885b-45fe-9f77-8ad14f9449a4)

2023-12-30 13:49 UTC, AkaShark commented
可以回头再开个分支专门再一起看看这个问题的

2023-12-30 13:50 UTC, tisfeng commented
不不，这里不要随便关闭 main 窗口，这是没道理的，我之前某些地方也只是将这个窗口移到图层下面。

你这里可以不用处理这个问题，后面在专门弄。

2023-12-30 13:57 UTC, AkaShark commented
okay 我给恢复了，是的看到之前都是直接back了，不过想请教下感觉关闭了main也是OK的呀，用户体验上呼出了其他窗口后关闭main也是合理的呀

2023-12-30 14:03 UTC, tisfeng commented
> okay 我给恢复了，是的看到之前都是直接back了，不过想请教下感觉关闭了main也是OK的呀，用户体验上呼出了其他窗口后关闭main也是合理的呀

因为窗口类型不同， main 窗口不同于悬浮窗口，悬浮窗口设计时就是一种轻量级窗口，在未使用时需要关闭，而 main 窗口和电脑上其他应用的窗口类型一样，除非用户手动关闭，否则我们不应该莫名关掉它。

2023-12-30 14:06 UTC, AkaShark commented
okk 理解了，那这个PR可以辛苦再帮忙Review下，我这边没啥问题啦

2023-12-30 14:07 UTC, tisfeng commented
> 因为发现显示主窗口会导致一些问题，所以目前默认隐藏了主窗口。
> 
> 主要的问题是，如果显示主窗口，在唤起其他查询窗口时，也会将主窗口显示在前台，感觉会很怪。
> 
> 我对窗口处理不是很了解，不知道如何解决，就干脆隐藏了。如果你熟悉这块，可以帮忙看一下。

我在某些地方将  main 窗口 orderBack，是因为发现在在唤起其他查询窗口时，也会将主窗口显示在前台，这不是我期望的，但我目前不知道如何处理，只能临时将它 orderBack 了。

2023-12-30 14:08 UTC, tisfeng commented
这个 PR 没问题，我先合并了。

2023-12-30 14:09 UTC, tisfeng approved these changes

2023-12-30 14:09 UTC, merged