add ali translate support
tisfeng/Easydict pull request #294
Opened 2023-12-30 17:05 UTC by choykarl

close #65

2023-12-30 17:08 UTC, choykarl commented
@tisfeng 不好意思，那个pr的分支被弄坏了，我这边一时半会可能整不好，不如重新pr一个来的快。

2024-01-01 06:41 UTC, tisfeng commented
@Kyle-Ye 帮忙看一下，如果代码没问题，稍后我就就合并了。

2024-01-01 12:27 UTC, Kyle-Ye commented on Easydict/Feature/Service/Ali/AliResponse.swift
> +    var Data: Data?
```suggestion
    var data: Data?
    ...

    enum CodingKeys: CodingKey {
        case data = "Data"
        ...
    }
```

2024-01-01 13:27 UTC, Kyle-Ye requested changes

2024-01-01 14:24 UTC, choykarl commented on Easydict/Feature/Service/Ali/AliService.swift
> +        let text = text.count > limit ? String(text[..<text.index(text.startIndex, offsetBy: limit)]) : text
done. 学习了👍

2024-01-01 15:01 UTC, Kyle-Ye approved these changes

2024-01-01 15:46 UTC, merged