fix: add some missing English translations
tisfeng/Easydict pull request #327
Opened 2024-01-15 05:41 UTC by phlpsong

missing English translations in the Menu and General tab.

2024-01-15 14:31 UTC, tisfeng requested changes

2024-01-15 14:37 UTC, phlpsong commented on Easydict/App/Localizable.xcstrings
> +            "state" : "needs_review",
OK, I thought it needed to be marked as this, changed.

2024-01-15 14:45 UTC, tisfeng commented
Please check all Localizable.xcstrings, including Chinese and English, mark them all as reviewed, some of them may not be used, just ignore them.

<img width="1108" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/fb2abf51-66d1-420a-b78e-27743bd5d5f9">

2024-01-15 16:33 UTC, tisfeng approved these changes

2024-01-15 16:55 UTC, Jerry23011 approved these changes

2024-01-15 16:56 UTC, Jerry23011 commented on Easydict/App/Localizable.xcstrings
> +            "value" : "Auto play pronunciation after querying English words"
leaving it here for later adjustments

2024-01-16 06:12 UTC, phlpsong commented
@tisfeng @Jerry23011 If there are no other issues, please kindly merge this.

2024-01-16 09:56 UTC, tisfeng commented
ok

2024-01-16 09:56 UTC, merged