fix: swift format while enable SwiftUI preview
tisfeng/Easydict pull request #328
Opened 2024-01-15 14:48 UTC by phlpsong

always getting `The file has been changed by another application` popup in Xcode while previewing SwiftUI views.

2024-01-15 15:52 UTC, tisfeng requested changes

2024-01-15 15:52 UTC, tisfeng commented on Easydict.xcodeproj/project.pbxproj
> +			shellScript = "# Type a script or drag a script file from your workspace to insert its path.\nif [ \"${ENABLE_PREVIEWS}\" = \"YES\" ]; then\n  echo \"Not running Swift Format for Xcode Previews\"\
```suggestion
			shellScript = "# Type a script or drag a script file from your workspace to insert its path.\nif [ \"${ENABLE_PREVIEWS}\" = \"YES\" ]; then\n  echo \"SwiftFormat skipped for Xcode Previews.\"\n  exit 0;\nfi\n\"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat\" \"$SRCROOT/$TARGET_NAME\" --swiftversion 5.7\n";
```

2024-01-15 20:29 UTC, CanglongCl approved these changes

2024-01-16 01:10 UTC, tisfeng approved these changes

2024-01-16 01:10 UTC, merged