[Refactor] Introduce a global context and migrate the updater controller into it
tisfeng/Easydict pull request #365
Opened 2024-01-25 19:32 UTC by CanglongCl

Fix `updaterController` difference in old and new app life circle. #363

2024-01-26 02:06 UTC, tisfeng commented
There is a warning when starting in old settings.

<img width="1077" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/c25cf488-7c35-4254-afb8-72fb320791fd">

2024-01-26 02:06 UTC, phlpsong commented on Easydict/NewApp/Utility/GlobalContext.swift
> +        let upadterHelper = SPUUpdaterHelper()
a typo here.

2024-01-26 03:11 UTC, tisfeng requested changes

2024-01-26 03:11 UTC, tisfeng commented on Easydict/NewApp/Utility/GlobalContext.swift
> +                true
The new updater delegate method doesn't work, still getting a warning, as well as `func feedURLString(for _: SPUUpdater) -> String?` above.

```
Warning: Background app automatically schedules for update checks but does not implement gentle reminders. As a result, users may not take notice to update alerts that show up in the background. Please visit https://sparkle-project.org/documentation/gentle-reminders for more information. This warning will only be logged once.
```

2024-01-26 14:04 UTC, phlpsong commented on Easydict/App/AppDelegate.h
> -@property (weak) IBOutlet SPUStandardUpdaterController *updaterController;
Since you have removed this, some setup code in `AppDelegate.m` for `SPUStandardUpdaterController `  could be removed too.

2024-01-26 14:23 UTC, phlpsong approved these changes

2024-01-26 14:49 UTC, AkaShark approved these changes

2024-01-27 01:50 UTC, tisfeng approved these changes

2024-01-27 01:50 UTC, merged