fix: shortcut bug
tisfeng/Easydict pull request #394
Opened 2024-02-07 14:00 UTC by AkaShark

closed https://github.com/tisfeng/Easydict/issues/391

2024-02-08 13:24 UTC, tisfeng requested changes
App crashed when I deleting clear input text shortcut 

<img width="1698" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/a8c58676-5bca-4ce8-9844-3cffc5f18108">

2024-02-08 13:51 UTC, AkaShark commented
okay, I will take a look at it tonight, whether your Mac language in Chinese?

2024-02-08 13:52 UTC, tisfeng commented
<img width="751" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2f06d52a-7160-4517-b690-3ddebeeddd18">

2024-02-08 15:24 UTC, tisfeng commented
Testing is fine now.

2024-02-08 15:25 UTC, tisfeng approved these changes

2024-02-08 15:42 UTC, phlpsong requested changes

2024-02-08 15:42 UTC, phlpsong commented on Easydict/NewApp/View/SettingView/Tabs/View/Shortcut/KeyHolderWrapper.swift
>                          confictAlterMessage = ShortcutConfictAlertMessage(title: String(localized: "shortcut_confict_title \(keyCombo!.keyEquivalentModifierMaskString + keyCombo!.characters)"), messa
The indent of this line is not adjusted correctly. And please make this line shorter if possible, like define `title` and `message` in a separate line.

2024-02-08 15:44 UTC, phlpsong commented on Easydict/NewApp/View/SettingView/Tabs/View/Shortcut/KeyHolderWrapper.swift
>                          confictAlterMessage = ShortcutConfictAlertMessage(title: String(localized: "shortcut_confict_title \(keyCombo!.keyEquivalentModifierMaskString + keyCombo!.characters)"), messa
Use `key` instead of `keyCombo!`.

2024-02-08 15:46 UTC, phlpsong commented on Easydict/NewApp/View/SettingView/Tabs/View/Shortcut/KeyHolderWrapper.swift
> +                Shortcut.shared.updateMenu(type)
This `if` branch could be omitted since you have the optional binding check for `keyCombo` below.

2024-02-08 15:55 UTC, phlpsong commented on Easydict/NewApp/View/SettingView/Tabs/View/Shortcut/KeyHolderWrapper.swift
> +                Shortcut.shared.updateMenu(type)
Apologies, this is fine. Please ignore this.

2024-02-08 16:24 UTC, phlpsong approved these changes

2024-02-09 01:29 UTC, tisfeng approved these changes

2024-02-09 01:29 UTC, merged