Migrate Automatically Check for Updates toggle from About tab to Advanced tab
tisfeng/Easydict pull request #444
Opened 2024-03-06 08:53 UTC by Jerry23011

Please tell me if I CVed the code right :)

2024-03-06 13:29 UTC, AkaShark approved these changes

2024-03-06 14:25 UTC, tisfeng requested changes
I think it would be better to place the AutoCheckUpdate option on the General tab, because it is a common feature for most apps.

The advanced tab should place some less common features,, or features in Easydict that are not well understood by the average user.

<img width="856" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/57598fbf-4d67-4f50-a359-4c8cfb40c7e1">

2024-03-06 14:38 UTC, tisfeng requested changes

2024-03-06 14:38 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
The `Latest version` could keep in About tab, we can add a `Check update` button in this page, like 1Password.

This makes it convenient for users to manually check for updates on the About tab, and also provides an alternative way  besides the menu icon.

<img width="856" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e74f2682-9893-4168-913e-6ed71603ee90">

<img width="816" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d01168c3-95c4-4337-9874-6626be3687d4">

2024-03-06 21:35 UTC, Jerry23011 commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
For the check for updates button, I think [CodeEdit](https://github.com/CodeEditApp/CodeEdit/blob/main/CodeEdit/Features/Settings/SettingsView.swift) has a pretty good approach to put it in general
<img width="827" alt="截屏2024-03-06 13 34 58" src="https://github.com/tisfeng/Easydict/assets/89069957/aaaec610-2e2a-43dc-8d59-2654df875265">

2024-03-07 02:57 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
Ok, it looks great, let's follow it.

2024-03-09 08:19 UTC, Jerry23011 commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
I've updated the code to fit the style of CodeEdit
<img width="932" alt="截屏2024-03-09 00 15 55" src="https://github.com/tisfeng/Easydict/assets/89069957/8b0894ab-2ff8-4f10-8107-905830b5b944">
<img width="932" alt="截屏2024-03-09 00 17 18" src="https://github.com/tisfeng/Easydict/assets/89069957/1ddd8473-5e7e-45b6-b387-5171c3e875fe">

2024-03-09 08:21 UTC, Jerry23011 commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
I think we can perhaps rewrite the About view later to have a horizontal layout. It doesn't look very modern at the moment

2024-03-09 14:35 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新（最新版本 %@）"
Yes, I agree with you.

2024-03-09 16:57 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新"
`auto_check_update` already exists.

<img width="1098" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/5f3f14f5-1506-4356-810e-ba0665d00972">

2024-03-09 22:29 UTC, Jerry23011 commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新"
These two cannot be deleted as they are both auto-generated. I check the code and found the previous one to be for the objc About view. I will push a commit to unify their translations.
<img width="1512" alt="截屏2024-03-09 14 25 20" src="https://github.com/tisfeng/Easydict/assets/89069957/b06f6d62-e774-4258-a31e-a9fc8ef6caec">

2024-03-10 03:05 UTC, phlpsong approved these changes

2024-03-10 04:15 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +            "value" : "自动检查应用程序更新"
ok

2024-03-10 04:22 UTC, tisfeng approved these changes
Looks good.

2024-03-10 05:31 UTC, merged