pref: shortcut store logic
tisfeng/Easydict pull request #446
Opened 2024-03-08 14:38 UTC by AkaShark

closed https://github.com/tisfeng/Easydict/issues/192

2024-03-09 04:54 UTC, tisfeng requested changes

2024-03-09 04:54 UTC, tisfeng commented on Easydict/NewApp/Feature/Shortcut/Shortcut.swift
> -            HotKeyCenter.shared.unregisterHotKey(with: type.rawValue)
When deleting the shortcut key, keyCombo is nil. If unregisterHotKey is not executed, the shortcut key will still be effective.

2024-03-09 16:52 UTC, tisfeng requested changes
Looks good.

2024-03-09 22:35 UTC, Jerry23011 approved these changes
The bug's gone, LGTM

2024-03-10 02:55 UTC, phlpsong approved these changes

2024-03-10 04:24 UTC, tisfeng approved these changes

2024-03-10 04:24 UTC, merged