fix: multi screen window show
tisfeng/Easydict pull request #450
Opened 2024-03-10 09:10 UTC by AkaShark

closed https://github.com/tisfeng/Easydict/issues/442

2024-03-10 15:14 UTC, phlpsong submitted a review, later dismissed
LGTM

2024-03-11 03:51 UTC, tisfeng commented on Easydict/Feature/Utility/EZCoordinateUtils/EZCoordinateUtils.m
> +            screen = NSScreen.mainScreen; // EZShowWindowMultiScreenFixed fixed in main screen
No, it should not use mainScreen here, it should use the screen when selecting words.

2024-03-11 04:05 UTC, tisfeng requested changes
Normally, the position of the word is basically the same as the mouse position, but if the user moves the mouse position quickly during the query, or even across multiple screens, the problem will be complicated, which I have not considered before.

I thought about it and felt that there is no need to add an additional option here. We should use the screen where the selected word is located, rather than the current mouse position.

Usually, the position of the word selection is basically consistent with the mouse position. However, if users quickly move the mouse during the query process, even across multiple screens, it will make this issue very complex, which I hadn't considered before.

After some thought, I feel that there is no need to add an additional option here. We should use the screen where the word selection is made instead of the current mouse position.

Adding an extra setting option may confuse users. Using the location of word selection aligns better with user intuition.

2024-03-11 05:23 UTC, AkaShark commented
okay I will fix it later

2024-03-12 05:01 UTC, AkaShark commented
I remove the picker from the settings page.  When the user starts the query I record the mouse-located screen,  and remove this record when the floating window closes.

2024-03-12 05:05 UTC, AkaShark commented
> I remove the picker from the settings page. When the user starts the query action I record the mouse-located screen and remove this record when the floating window closes.

2024-03-12 15:35 UTC, tisfeng requested changes
I tried it, but the current code does not work https://github.com/tisfeng/Easydict/issues/442#issuecomment-1987531812 :

Get the word on screen A, then move the mouse to screen B, and then use the shortcut keys to translate the word. The query window should be displayed at the word pick-up position on screen A.

2024-03-12 15:38 UTC, tisfeng commented
This problem can be a bit complex, involving multiple screens of records and the handling of the location of the display query window.

If you're not good at solving it, I can take over later.

2024-03-12 16:03 UTC, AkaShark commented
Oh, I now understand your issue. I didn't consider issue #442  earlier and only focused on the mouse move duration during query translation. To address this, I will record the screen when starting a query like this
```
- (void)startQueryText:(NSString *)text actionType:(EZActionType)actionType {
    // record current screen when start query
    NSScreen *current = [EZCoordinateUtils screenForPoint: [NSEvent mouseLocation]];
    EZCoordinateUtils.startQueryScreen = current;
```
Let me try it first. I'll ask for your help if I find it difficult for me.

2024-03-12 16:14 UTC, AkaShark commented
@tisfeng  My idea is to record the screen when a word is selected for translation and display a query window on this screen. For other modes of translation, the screen will still be recorded when the query is initiated. What do you think about it?

2024-03-12 16:25 UTC, tisfeng commented
I'm not so sure, you can try it and then we'll test it.

2024-03-12 16:28 UTC, AkaShark commented
> I'm not so sure, you can try it and then we'll test it.

okk

2024-03-14 03:25 UTC, tisfeng requested changes
It still doesn't work.

Although the latest code can record screen A https://github.com/tisfeng/Easydict/pull/450#pullrequestreview-1931433425 , the position of the query window displayed when using the shortcut key to stroke the words to translate is inaccurate, and there is a problem that the query window flickers between screen A and screen B. 

It's not easy for me to record a video to show you this problem,  I suggest you test it yourself using multiple screens, its very easy to reproduce.

2024-06-07 14:16 UTC, tisfeng commented
@AkaShark  When you have time, please continue pushing this PR.

2024-06-08 13:35 UTC, AkaShark commented
> @AkaShark When you have time, please continue pushing this PR.

okay, I will try to fix it in the last few days

2024-06-24 12:39 UTC, AkaShark commented
I'm sorry I've been a little busy lately. I'll finish this issue as soon as possible.

2024-06-24 13:22 UTC, tisfeng commented
ok, you can schedule as you see fit.

2025-02-14 12:40 UTC, closed without merging