fix baidu translate
tisfeng/Easydict pull request #482
Opened 2024-03-31 12:09 UTC by choykarl

#481 
先将接口相应切换到旧版本让服务可用，后面再做成可配置key的。

2024-03-31 12:15 UTC, phlpsong approved these changes

2024-04-01 02:05 UTC, tisfeng commented
行，那这次先修复，稍后我们发个更新版本。

后面再支持官方百度翻译接口。

2024-04-01 03:09 UTC, tisfeng requested changes

2024-04-01 03:09 UTC, tisfeng commented on Easydict/Feature/Service/Baidu/EZBaiduTranslate.m
> +        cookie = [NSString stringWithFormat:@"%@%@", cookie, @";smallFlowVersion=old;"];
试了一下，还真行，你怎么找到这个方法的 🤣

2024-04-01 07:51 UTC, Jerry23011 approved these changes
Latest code works on my end

2024-04-01 14:44 UTC, choykarl commented on Easydict/Feature/Service/Baidu/EZBaiduTranslate.m
> +        cookie = [NSString stringWithFormat:@"%@%@", cookie, @";smallFlowVersion=old;"];
我看百度翻译的页面有个返回旧版，我就在旧版的请求里找了找，感觉这个字段像是控制的，一试还真行😄

2024-04-01 15:25 UTC, tisfeng commented on Easydict/Feature/Service/Baidu/EZBaiduTranslate.m
> +        cookie = [NSString stringWithFormat:@"%@%@", cookie, @";smallFlowVersion=old;"];
可以 😆

2024-04-01 15:37 UTC, tisfeng approved these changes

2024-04-01 15:37 UTC, merged