Added support for translation to Brazilian Portuguese.
tisfeng/Easydict pull request #586
Opened 2024-06-12 09:38 UTC by NeverAgain11

#585

2024-06-12 09:39 UTC, NeverAgain11 commented
@tisfeng 

新增支持翻译到巴西葡萄牙语时，用 pt-BR 时请求翻译出现错误.

Bind 翻译的错误是:

bing json parse failed
{
  "errorMessage" : "",
  "statusCode" : 400
}}

DeepL 的错误是:

Request failed: bad request (400)
Invalid Request

能帮忙看看是什么问题么？

2024-06-12 16:30 UTC, tisfeng commented
ok，明天我看看。

2024-06-12 17:37 UTC, Jerry23011 commented
<img width="472" alt="截屏2024-06-13 01 37 00" src="https://github.com/tisfeng/Easydict/assets/89069957/b723e3e5-56e2-4cca-996f-b00f30cf43e7">
DeepL works on my end

2024-06-12 18:03 UTC, Jerry23011 commented
As for Bing, it just doesn't seem to support `pt-BR`?
![截屏2024-06-13 02 00 12](https://github.com/tisfeng/Easydict/assets/89069957/a99a93c0-f5ed-4c9b-9bc6-4077036933b2)
<img width="946" alt="截屏2024-06-13 02 00 47" src="https://github.com/tisfeng/Easydict/assets/89069957/3f4cc931-c933-4441-9d13-e418e4ded701">

2024-06-13 05:14 UTC, NeverAgain11 commented
@Jerry23011 Could you try to translate from Chinese text to pt-BR?

2024-06-13 07:04 UTC, Jerry23011 commented
> @Jerry23011 Could you try to translate from Chinese text to pt-BR?

When targeting pt-BR, DeepL says Invalid target_lang
```json
{
  "jsonrpc": "2.0",
  "id": 150256000,
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": {
      "what": "Invalid target_lang."
    }
  }
}
```

2024-06-13 15:13 UTC, tisfeng commented
The official API of DeepL supports PT-BR language, but the web version of our API does not support it.

<img width="1233" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/61a953b3-e535-46c7-912e-d6907956d552">

2024-06-13 15:17 UTC, tisfeng commented
I just added DeepL support for regional variant languages, like pt-BR 1cc75611

<img width="417" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/b4dbd1db-60a1-4dd3-a4c0-68ba171ebab2">

2024-06-13 16:21 UTC, tisfeng commented
Note that I just debugged the Bing web API and found that the current code for the Portuguese language is wrong, it's a bit strange, for Portuguese Portuguese it's `pt-PT`, for Brazilian Portuguese it's `pt` 😓

I have fixed it adde77e1 .

[Bing Brazilian Portuguese translate](https://www.bing.com/translator/?text=%E5%85%AB%E5%8D%81%E4%B8%83%E5%B9%B4%E5%89%8D%EF%BC%8C%E6%88%91%E4%BB%AC%E7%9A%84%E7%88%B6%E8%BE%88%E4%BB%AC%E5%9C%A8%E8%BF%99%E5%9D%97%E9%99%86%E5%9C%B0%E4%B8%8A%E5%BB%BA%E8%B5%B7%E4%BA%86%E4%B8%80%E4%B8%AA%E6%96%B0%E7%9A%84%E5%9B%BD%E5%AE%B6%EF%BC%8C%E5%AE%83%E5%AD%95%E8%82%B2%E4%BA%8E%E8%87%AA%E7%94%B1%EF%BC%8C%E5%B9%B6%E5%A5%89%E8%A1%8C%E4%BA%BA%E4%BA%BA%E7%94%9F%E8%80%8C%E5%B9%B3%E7%AD%89%E7%9A%84%E4%B8%BB%E5%BC%A0%E3%80%82&from=zh-Hans&to=pt-BR)



<img width="1674" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/21b8b1a8-d750-4b54-8853-8b33d11e751b">

<img width="1670" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/4fda31e9-f0a7-42bb-a320-4b203654ae0a">

2024-06-14 01:58 UTC, tisfeng requested changes
Please check if other services support Brazilian Portuguese language, such as Baidu Translate, it is supported.

<img width="1516" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/b2eaa275-b3f2-4a3e-8bf3-a289c608bcf0">

2024-06-14 14:57 UTC, tisfeng commented on Easydict/objc/Service/Language/EZLanguageModel.m
> +        portuguese.voiceName = @"Joana";
Here Portugal has the wrong voiceName, I changed it to `Joana`.

A lot of this code is sample code, I wrote it with the help of ChatGPT, so I can't guarantee that it's correct 😥
 
<img width="1673" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/bedbed0d-9c85-479e-858c-0f616e49f7fe">

2024-06-15 15:29 UTC, Jerry23011 commented
The latest changes works on my end

2024-06-17 06:27 UTC, NeverAgain11 commented
I checked other services and added support for Baidu, Google and Niu.
The Google translation has the same effect when using pt, pt-PT and pt-BR.

2024-06-17 15:12 UTC, tisfeng commented
> The Google translation has the same effect when using pt, pt-PT and pt-BR.

It seems Google Translate doesn't support pt-BR, and the web version doesn't have the Brazilian Portuguese language option either.

2024-06-18 15:09 UTC, tisfeng approved these changes

2024-06-18 15:09 UTC, merged