fix: move service refresh list
tisfeng/Easydict pull request #641
Opened 2024-08-13 04:59 UTC by choykarl

2024-08-13 14:53 UTC, tisfeng requested changes

2024-08-13 14:53 UTC, tisfeng commented on Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift
> +    @Published private(set) var services: [QueryService]
`services` is private, it's not used outside, what's the point of changing it to `@Published`?

And, what problem will the old code cause?

2024-08-14 01:26 UTC, choykarl commented on Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift
> +    @Published private(set) var services: [QueryService]
现在切换服务顺序不会刷新了

2024-08-14 15:13 UTC, tisfeng commented on Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift
> +    @Published private(set) var services: [QueryService]
哦，明白了，我的问题，之前修改 dced9d2 把这里的 `@Published` 弄丢了 😥

2024-08-14 15:19 UTC, tisfeng commented
这问题有点烦，过两天发个修复版本吧。

2024-08-14 15:20 UTC, tisfeng approved these changes

2024-08-14 15:20 UTC, merged

2024-08-14 15:22 UTC, choykarl commented
我觉得可以，确实有点影响体验