pre validate service
tisfeng/Easydict pull request #727
Opened 2024-11-18 03:30 UTC by AkaShark

closed https://github.com/tisfeng/Easydict/issues/714

2024-11-19 01:01 UTC, CanglongCl commented
@AkaShark Hi I made some changes to your branch. Now while user click the toggle, it will be turned into a `ProgressView` individually. Error message alert is also implemented.

2024-11-19 02:00 UTC, AkaShark commented
> @AkaShark Hi I made some changes to your branch. Now while user click the toggle, it will be turned into a `ProgressView` individually. Error message alert is also implemented.

Thank you for your commit! As someone new to SwiftUI, your code helps me learn more, and it improves this feature significantly.

2024-11-19 14:00 UTC, tisfeng commented on Easydict/App/Localizable.xcstrings
> +      "extractionState" : "stale",
If this string is not used, please remove it.

2024-11-19 14:27 UTC, tisfeng commented on Easydict/Swift/View/SettingView/Tabs/TabView/ServiceTab.swift
> +//                self.objectWillChange.send()
Can this code be removed?

2024-11-19 15:14 UTC, tisfeng commented
I improved the UI, aligning the ProgressView and Toggle 0b51d9ad

## Before
<img width="900" alt="image" src="https://github.com/user-attachments/assets/d5d86b17-536c-4e7d-8fe9-c601cb61fc93">

## Now 
<img width="900" alt="image" src="https://github.com/user-attachments/assets/4540e85c-6ece-4039-ad52-9388034f8a27">

2024-11-19 15:23 UTC, tisfeng requested changes
For the new localizations, we need to add translations in English, Simplified Chinese, Traditional Chinese, and Slovak.

We just need to ensure that the translations in Chinese and English are correct. As for other languages, such as Slovak, translation tools can be used. 

I usually use Cursor for auto-completion, and later there will be users familiar with that language to proofread https://github.com/tisfeng/Easydict/pull/708#issuecomment-2447086972

<img width="1666" alt="image" src="https://github.com/user-attachments/assets/a8227401-fe0c-44f4-ac48-8a54dbd3b3fd">


<img width="1285" alt="image" src="https://github.com/user-attachments/assets/450f94ab-2509-493f-9741-11ddd623600a">

2024-11-19 15:34 UTC, tisfeng commented
I'm considering removing the en-CA localization because it's almost the same as en, and we're not familiar with it. It's not worth spending time to differentiate between them. 

Initially, we added en-CA just to provide users with a localization example https://github.com/tisfeng/Easydict/pull/231. Moreover, there's now a better Slovak localization example https://github.com/tisfeng/Easydict/pull/668.

2024-11-19 16:00 UTC, AkaShark commented
> For the new localizations, we need to add translations in English, Simplified Chinese, Traditional Chinese, and Slovak.对于新的本地化，我们需要添加英语、简体中文、繁体中文和斯洛伐克语的翻译。
> 
> We just need to ensure that the translations in Chinese and English are correct. As for other languages, such as Slovak, translation tools can be used.我们只需要确保中文和英文的翻译是正确的。至于其他语言，比如斯洛伐克语，可以使用翻译工具。
> 
> I usually use Cursor for auto-completion, and later there will be users familiar with that language to proofread [#708 (comment)](https://github.com/tisfeng/Easydict/pull/708#issuecomment-2447086972)我一般都是用Cursor来做自动补全，后面会有熟悉那个语言的用户来校对 [#708 (comment)](https://github.com/tisfeng/Easydict/pull/708#issuecomment-2447086972)
> 
> <img alt="image" width="1666" src="https://private-user-images.githubusercontent.com/25194972/387716460-a8227401-fe0c-44f4-ac48-8a54dbd3b3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzEyOTcsIm5iZiI6MTczMjAzMDk5NywicGF0aCI6Ii8yNTE5NDk3Mi8zODc3MTY0NjAtYTgyMjc0MDEtZmUwYy00NGY0LWFjNDgtOGE1NGRiZDNiM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjY5NWJjYTVkZjNmNzFmZTVhYWEzNTc5YTFhNzUyZTRiZWJjMTk1ZjVjYmVkYjcxY2Y0YjNmYjMyZDc4YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mxh4yJX4ZEA9-thpaOElCYYuZEr5rpwsysivaFCZpyw"> <img alt="image" width="1285" src="https://private-user-images.githubusercontent.com/25194972/387716318-450f94ab-2509-493f-9741-11ddd623600a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzEyOTcsIm5iZiI6MTczMjAzMDk5NywicGF0aCI6Ii8yNTE5NDk3Mi8zODc3MTYzMTgtNDUwZjk0YWItMjUwOS00OTNmLTk3NDEtMTFkZGQ2MjM2MDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NzU1NjU3ZTkxMDE1YzczYmZiZDFiZjY4MDc3NjFkYTEwYjRiYzhhZjIzZTYwOTViMTAxN2Y2NDYyNzJhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cmzn1ihJXh9E1bvrBB-uMwucTGIoUMzH0kU5kFNTF3A">

That seems like a good way.

2024-11-21 12:55 UTC, tisfeng approved these changes
Looks good.

2024-11-21 12:55 UTC, merged

2024-11-21 19:00 UTC, Jerry23011 commented
> I'm considering removing the en-CA localization because it's almost the same as en, and we're not familiar with it. It's not worth spending time to differentiate between them.
> 
> Initially, we added en-CA just to provide users with a localization example #231. Moreover, there's now a better Slovak localization example #668.

+1 for this